- name: Restart named service
  service:
    name: named
    state: restarted

- name: Restart httpd service
  service:
    name: httpd
    state: restarted

- name: Restart systemd
  command: systemctl daemon-reload
  become: yes