- name: Restart httpd service
  service:
    name: httpd
    state: restarted

- name: Restart postfix service
  service:
    name: postfix
    state: restarted

- name: Restart dovecot service
  service:
    name: dovecot
    state: restarted