# Running this playbook: ansible-playbook playbook.yml -i inventory/hosts

- hosts: all
  user: centos
  become: yes
  become_user: root
  vars:
    hostname: saarniit-test
    domain_name: sa.cs.ut.ee
    external_ip: 172.17.91.211
    reverse_ip: 91.17.172
    subdomain: 172.17.91
    host_portion: 211
    mysql_root_password: andmebaas123

  roles:
  #- etais
  #- dns
  - apache

  tasks:
  - name: Testing this out
    debug: msg="Hello from user {{ ansible_user_id }} on server {{ ansible_hostname }}!"