# --- installing necessary packages ---
- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

- name: Install bind and bind-util packages
  dnf:
    name:
      - bind
      - bind-utils
    state: latest

# --- opening ports and services ---
- name: Permanently enable dns service
  ansible.posix.firewalld:
    service: dns
    state: enabled
    permanent: true
    immediate: true # this is basically 'firewall-cmd --reload'

- name: Permanently enable 8301/udp port
  ansible.posix.firewalld:
    port: 8301/udp
    state: enabled
    permanent: true
    immediate: true # this is basically 'firewall-cmd --reload'

- name: Permanently enable 8301/tcp port
  ansible.posix.firewalld:
    port: 8301/tcp
    state: enabled
    permanent: true
    immediate: true # this is basically 'firewall-cmd --reload'

# --- disabling IPv6 ---
- name: Disable IPv6
  copy:
    src: 70-ipv6.conf
    dest: /etc/sysctl.d/70-ipv6.conf
    owner: root
    group: root
    mode: '0644'

- name: Change net.ipv6.conf.default.disable_ipv6 to 1.
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Change net.ipv6.conf.all.disable_ipv6 to 1.
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

# --- changing hostname ---
- name: Inserts into hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Inserts into hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

# --- creating log locations ---
- name: Create log directory into /var/named
  file:
    path: /var/named/log
    state: directory
    owner: named
    group: named
    mode: '0750'

- name: Create the log files in /var/named/log
  file:
    path: /var/named/log/{{ item }} # item is taken from loop
    state: touch
    owner: named
    group: named
    mode: '0600'
  loop:
    - default
    - auth_servers
    - zone_transfers
    - client_security
    - queries
    - query-errors

- name: Replace the default logging options
  copy:
    src: named.conf
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0644'

# --- start the name server ---
- name: Start and enable named service
  service:
    name: named
    state: started
    enabled: true

# --- configure machine to use local DNS ---
- name: Configure machine to use local DNS server for all queries
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: named
    mode: '0644'

# --- create zone file ---
- name: Create zone file <hostname>.<domain_name> into /etc/named
  template:
    src: "main-zone.j2"
    dest: "/etc/named/{{ hostname }}.{{ domain_name }}"
    owner: root
    group: named
    mode: '0644'
  notify: Restart named service # triggers handler

- name: Add main zone clause to /etc/named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0644'
  notify: Restart named service # triggers handler

# --- create reverse zone file ---
- name: Create reverse zone file <subdomain> into /etc/named
  template:
    src: "reverse-zone.j2"
    dest: "/etc/named/{{ subdomain }}"
    owner: root
    group: named
    mode: '0644'
  notify: Restart named service # triggers handler

- name: Add reverse zone clause to /etc/named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0644'
  notify: Restart named service # triggers handler